version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - minio
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/SAHAND
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: "@Amin0076"
      MINIO_ENDPOINT: http://minio:9000
      MINIO_ACCESS_KEY: minioSahand
      MINIO_SECRET_KEY: minioSahandSecret
    restart: unless-stopped

  postgres:
    image: postgres:14
    environment:
      POSTGRES_DB: SAHAND
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "@Amin0076"
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  minio:
    image: minio/minio
    environment:
      MINIO_ROOT_USER: minioSahand
      MINIO_ROOT_PASSWORD: minioSahandSecret
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --console-address ":9001"
    volumes:
      - miniodata:/data
    restart: unless-stopped

volumes:
  pgdata:
  miniodata:
