version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sahand-app
    depends_on:
      - db
      - minio
    environment:
      - DB_HOST=host.docker.internal
      - DB_PORT=5432
      - DB_NAME=SAHAND
      - DB_USER=postgres
      - DB_PASSWORD=@Amin0076
      - MINIO_HOST=minio
      - MINIO_PORT=9000
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    ports:
      - "8080:8080"
    networks:
      - backend

  db:
    image: postgres:15
    container_name: sahand-db
    environment:
      POSTGRES_DB: SAHAND
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "@Amin0076"
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend

  minio:
    image: minio/minio
    container_name: sahand-minio
    command: server --console-address ":9001" /data
    ports:
      - "9000:9000"  # S3 API
      - "9001:9001"  # Console
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - miniodata:/data
    networks:
      - backend

volumes:
  pgdata:
  miniodata:

networks:
  backend:
