version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sahand-app
    depends_on:
      - db
      - minio
    env_file:
      - .env
    ports:
      - "8080:8080"
    networks:
      - backend

  db:
    image: postgres:15
    container_name: sahand-db
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend

  minio:
    image: minio/minio
    container_name: sahand-minio
    command: server --console-address ":9001" /data
    ports:
      - "9000:9000"  # S3 API
      - "9001:9001"  # Console
    env_file:
      - .env
    volumes:
      - miniodata:/data
    networks:
      - backend

volumes:
  pgdata:
  miniodata:

networks:
  backend:
