version: '3.8'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: messenger
      POSTGRES_USER: amin
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"

  kafka:
    image: bitnami/kafka:latest
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_LISTENERS=PLAINTEXT://:9092
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper

  zookeeper:
    image: bitnami/zookeeper:latest
    ports:
      - "2181:2181"

  backend:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - kafka
      - postgres