version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sahand-app
    depends_on:
      - minio
    environment:
      - DB_HOST=host.docker.internal
      - MINIO_HOST=host.docker.internal
    ports:
      - "8080:8080"
    networks:
      - backend

  minio:
    image: minio/minio
    container_name: sahand-minio
    command: server --console-address ":9001" /data
    ports:
      - "9000:9000"  # S3 API
      - "9001:9001"  # Console
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    volumes:
      - miniodata:/data
    networks:
      - backend

volumes:
  miniodata:

networks:
  backend:
