spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/SAHAND}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:@Amin0076}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
minio:
  url: ${MINIO_ENDPOINT:http://localhost:9000/}
  access-key: ${MINIO_ACCESS_KEY:minioSahand}
  secret-key: ${MINIO_SECRET_KEY:minioSahandSecret}
  bucket: Sahand
