spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/SAHAND
    username: postgres
    password: "@Amin0076"
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: false
        show_sql: true

minio:
  url: http://${MINIO_HOST:localhost}:9000/

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
