spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/SAHAND
    username: postgres
    password: "@Amin0076"
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: false
        show_sql: true
      leve
#  security:
#    user:
#      name: admin
#      password: admin
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
