spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/SAHAND
    username: postgres
    password: "@Amin0076"
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        show_sql: true
#  security:
#    user:
#      name: admin
#      password: admin
minio:
  url: http://localhost:9000
  access-key: Amin
  secret-key: "@Amin0076"
  bucket: SahandBucket
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
